package melonslise.lambda.common.sound;

import melonslise.lambda.common.sound.api.SoundEventNamed;
import melonslise.lambda.utility.LambdaUtilities;
import net.minecraft.util.SoundEvent;
import net.minecraftforge.event.RegistryEvent;

// TODO Move to client?
public class LambdaSounds
{
	public static SoundEvent
	item_smallmedkit = new SoundEventNamed(LambdaUtilities.createLambdaDomain("item.smallmedkit")),
	item_gunpickup = new SoundEventNamed(LambdaUtilities.createLambdaDomain("item.gunpickup")),

	item_medshot = new SoundEventNamed(LambdaUtilities.createLambdaDomain("item.medshot")),
	item_medcharge = new SoundEventNamed(LambdaUtilities.createLambdaDomain("item.medcharge")),
	item_medshotno = new SoundEventNamed(LambdaUtilities.createLambdaDomain("item.medshotno")),

	item_suitchargeok = new SoundEventNamed(LambdaUtilities.createLambdaDomain("item.suitchargeok")),
	item_suitcharge = new SoundEventNamed(LambdaUtilities.createLambdaDomain("item.suitcharge")),
	item_suitchargeno = new SoundEventNamed(LambdaUtilities.createLambdaDomain("item.suitchargeno")),

	denyselect = new SoundEventNamed(LambdaUtilities.createLambdaDomain("denyselect")),

	zap = new SoundEventNamed(LambdaUtilities.createLambdaDomain("zap")),

	projectile_bullet_hitbody = new SoundEventNamed(LambdaUtilities.createLambdaDomain("projectile.bullet.hit_body")),
	projectile_bullet_ricochet = new SoundEventNamed(LambdaUtilities.createLambdaDomain("projectile.bullet.ricochet")),
	projectile_bolt_hit = new SoundEventNamed(LambdaUtilities.createLambdaDomain("projectile.bolt.hit")),
	projectile_bolt_hitbody = new SoundEventNamed(LambdaUtilities.createLambdaDomain("projectile.bolt.hit_body")),

	alien_headcrab_alert = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.headcrab.alert")),
	alien_headcrab_attack = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.headcrab.attack")),
	alien_headcrab_die = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.headcrab.die")),
	alien_headcrab_idle = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.headcrab.idle")),
	alien_headcrab_pain = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.headcrab.pain")),
	alien_headcrab_bite = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.headcrab.bite")),

	alien_zombie_miss = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.zombie.miss")),
	alien_zombie_strike = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.zombie.strike")),
	alien_zombie_alert = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.zombie.alert")),
	alien_zombie_attack = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.zombie.attack")),
	alien_zombie_idle = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.zombie.idle")),
	alien_zombie_pain = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.zombie.pain")),

	alien_vortigaunt_alert = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.vortigaunt.alert")),
	alien_vortigaunt_die = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.vortigaunt.die")),
	alien_vortigaunt_pain = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.vortigaunt.pain")),
	alien_vortigaunt_word = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.vortigaunt.word")),
	alien_vortigaunt_shoot = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.vortigaunt.shoot")),

	alien_houndeye_alert = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.houndeye.alert")),
	alien_houndeye_attack = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.houndeye.attack")),
	alien_houndeye_blast = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.houndeye.blast")),
	alien_houndeye_die = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.houndeye.die")),
	alien_houndeye_hunt = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.houndeye.hunt")),
	alien_houndeye_idle = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.houndeye.idle")),
	alien_houndeye_pain = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.houndeye.pain")),

	alien_barnacle_alert = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.barnacle.alert")),
	alien_barnacle_bite = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.barnacle.bite")),
	alien_barnacle_chew = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.barnacle.chew")),
	alien_barnacle_die = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.barnacle.die")),
	alien_barnacle_tongue = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.barnacle.tongue")),

	alien_hornet_buzz = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.hornet.buzz")),
	alien_hornet_hit = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.hornet.hit")),

	alien_snark_deploy = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.snark.deploy")),
	alien_snark_hunt = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.snark.hunt")),
	alien_snark_die = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.snark.die")),
	alien_snark_blast = new SoundEventNamed(LambdaUtilities.createLambdaDomain("alien.snark.blast")),

	sentry_deploy = new SoundEventNamed(LambdaUtilities.createLambdaDomain("sentry.deploy")),
	sentry_ping = new SoundEventNamed(LambdaUtilities.createLambdaDomain("sentry.ping")),
	sentry_die = new SoundEventNamed(LambdaUtilities.createLambdaDomain("sentry.die")),

	weapon_glock_load = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.glock.load")),
	weapon_glock_unload = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.glock.unload")),
	weapon_glock_shot = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.glock.shot")),

	weapon_mp_load = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.mp.load")),
	weapon_mp_unload = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.mp.unload")),
	weapon_mp_shot = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.mp.shot")),
	weapon_mp_grenade = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.mp.grenade")),

	weapon_spas_load = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.spas.load")),
	weapon_spas_shot_singlebarrel = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.spas.shot.single_barrel")),
	weapon_spas_shot_doublebarrel = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.spas.shot.double_barrel")),
	weapon_spas_cock = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.spas.cock")),
	weapon_spas_shell = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.spas.shell")),

	weapon_python_load = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.python.load")),
	weapon_python_shot = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.python.shot")),
	weapon_python_cock = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.python.cock")),

	weapon_crossbow_load = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.crossbow.load")),
	weapon_crossbow_shot = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.crossbow.shot")),

	weapon_rpg_shot = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.rpg.shot")),
	weapon_rpg_rocket = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.rpg.rocket")),

	weapon_tau_shot = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.tau.shot")),
	weapon_tau_charge = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.tau.charge")),
	weapon_tau_discharge = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.tau.discharge")),

	weapon_gluon_charge = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.gluon.charge")),
	weapon_gluon_beam = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.gluon.beam")),
	weapon_gluon_discharge = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.gluon.discharge")),

	weapon_hivehand_shot = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.hivehand.shot")),

	weapon_grenade_hit = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.grenade.hit")),

	weapon_tripmine_deploy = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.tripmine.deploy")),
	weapon_tripmine_charge = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.tripmine.charge")),
	weapon_tripmine_activate = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.tripmine.activate")),

	weapon_dryfire = new SoundEventNamed(LambdaUtilities.createLambdaDomain("weapon.dryfire")),

	suit_hazard_bell = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.bell")),
	suit_hazard_logon = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.logon")),
	suit_hazard_powermove = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.powermove")),
	suit_hazard_powerarmor = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.powerarmor")),
	suit_hazard_atmospherics = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.atmospherics")),
	suit_hazard_vitalsigns = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.vitalsigns")),
	suit_hazard_automedic = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.automedic")),
	suit_hazard_weaponselect = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.weaponselect")),
	suit_hazard_munitionview = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.munitionview")),
	suit_hazard_communications = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.communications")),
	suit_hazard_safeday = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.safeday")),
	suit_hazard_beep = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.beep")),
	suit_hazard_health_dropping = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.health_dropping")),
	suit_hazard_health_critical = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.health_critical")),
	suit_hazard_evacuate = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.evacuate")),
	suit_hazard_immediately = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.immediately")),
	suit_hazard_near_death = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.near_death")),
	suit_hazard_seek_medic = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.seek_medic")),
	suit_hazard_warning = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.warning")),
	suit_hazard_shock = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.shock")),
	suit_hazard_heat = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.heat")),
	suit_hazard_boop = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.boop")),
	suit_hazard_toxins = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.toxins")),
	suit_hazard_minor_lacerations = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.minor_lacerations")),
	suit_hazard_major_lacerations = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.major_lacerations")),
	suit_hazard_minor_fracture = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.minor_fracture")),
	suit_hazard_major_fracture = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.major_fracture")),
	suit_hazard_blood_loss = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.blood_loss")),
	suit_hazard_internal_bleeding = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.internal_bleeding")),
	suit_hazard_flatline = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.flatline")),
	suit_hazard_hiss = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.hiss")),
	suit_hazard_morphine = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.morphine")),
	suit_hazard_blip = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.blip")),
	suit_hazard_radiation = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.radiation")),
	suit_hazard_chemical = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.chemical")),
	suit_hazard_biohazard = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.biohazard")),
	suit_hazard_fuzz = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.fuzz")),
	suit_hazard_power_restored = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.power_restored")),
	suit_hazard_percent = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.percent")),
	suit_hazard_power_level = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.power_level")),
	suit_hazard_ammo_depleted = new SoundEventNamed(LambdaUtilities.createLambdaDomain("suit.hazard.ammo_depleted"));

	private LambdaSounds() {};

	public static void register(RegistryEvent.Register<SoundEvent> event)
	{
		event.getRegistry().registerAll
		(
			item_smallmedkit,
			item_gunpickup,
			item_medshot,
			item_medcharge,
			item_medshotno,
			item_suitchargeok,
			item_suitcharge,
			item_suitchargeno,
			denyselect,
			zap,
			projectile_bullet_hitbody,
			projectile_bullet_ricochet,
			projectile_bolt_hitbody,
			projectile_bolt_hit,
			alien_headcrab_alert,
			alien_headcrab_attack,
			alien_headcrab_die,
			alien_headcrab_idle,
			alien_headcrab_pain,
			alien_headcrab_bite,
			alien_zombie_miss,
			alien_zombie_strike,
			alien_zombie_alert,
			alien_zombie_attack,
			alien_zombie_idle,
			alien_zombie_pain,
			alien_vortigaunt_alert,
			alien_vortigaunt_die,
			alien_vortigaunt_pain,
			alien_vortigaunt_word,
			alien_vortigaunt_shoot,
			alien_houndeye_alert,
			alien_houndeye_attack,
			alien_houndeye_blast,
			alien_houndeye_die,
			alien_houndeye_hunt,
			alien_houndeye_idle,
			alien_houndeye_pain,
			alien_barnacle_alert,
			alien_barnacle_bite,
			alien_barnacle_chew,
			alien_barnacle_die,
			alien_barnacle_tongue,
			alien_hornet_buzz,
			alien_hornet_hit,
			alien_snark_deploy,
			alien_snark_hunt,
			alien_snark_die,
			alien_snark_blast,
			sentry_deploy,
			sentry_ping,
			sentry_die,
			weapon_glock_load,
			weapon_glock_unload,
			weapon_glock_shot,
			weapon_mp_load,
			weapon_mp_unload,
			weapon_mp_shot,
			weapon_mp_grenade,
			weapon_spas_load,
			weapon_spas_shot_singlebarrel,
			weapon_spas_shot_doublebarrel,
			weapon_spas_cock,
			weapon_spas_shell,
			weapon_python_load,
			weapon_python_shot,
			weapon_python_cock,
			weapon_crossbow_load,
			weapon_crossbow_shot,
			weapon_rpg_shot, 
			weapon_rpg_rocket,
			weapon_tau_shot,
			weapon_tau_charge,
			weapon_tau_discharge,
			weapon_gluon_charge,
			weapon_gluon_beam,
			weapon_gluon_discharge,
			weapon_hivehand_shot,
			weapon_grenade_hit,
			weapon_tripmine_deploy,
			weapon_tripmine_charge,
			weapon_tripmine_activate,
			weapon_dryfire,
			suit_hazard_bell,
			suit_hazard_logon, 
			suit_hazard_powermove,
			suit_hazard_powerarmor,
			suit_hazard_atmospherics,
			suit_hazard_vitalsigns,
			suit_hazard_automedic,
			suit_hazard_weaponselect,
			suit_hazard_munitionview,
			suit_hazard_communications,
			suit_hazard_safeday,
			suit_hazard_beep,
			suit_hazard_health_dropping,
			suit_hazard_health_critical,
			suit_hazard_evacuate,
			suit_hazard_immediately,
			suit_hazard_near_death,
			suit_hazard_seek_medic,
			suit_hazard_warning,
			suit_hazard_shock,
			suit_hazard_heat,
			suit_hazard_boop,
			suit_hazard_toxins,
			suit_hazard_minor_lacerations,
			suit_hazard_major_lacerations,
			suit_hazard_minor_fracture,
			suit_hazard_major_fracture,
			suit_hazard_blood_loss,
			suit_hazard_internal_bleeding,
			suit_hazard_flatline,
			suit_hazard_hiss,
			suit_hazard_morphine, 
			suit_hazard_blip,
			suit_hazard_radiation,
			suit_hazard_chemical,
			suit_hazard_biohazard,
			suit_hazard_fuzz,
			suit_hazard_power_restored,
			suit_hazard_percent,
			suit_hazard_power_level,
			suit_hazard_ammo_depleted
		);
	}
}